### ISSUE TITLE
Condition support

### ISSUE THREAD

**Issue by ipmb** [MacHu-GWU/cottonformation-project#4]
I searched around a bit and couldn't find an implementation of the [Condition intrinsic functions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/conditions-section-structure.html#conditions-section-structure-functions). Does cottonformation have a solution for that currently?

**Comment by ipmb** [comment]
It looks Conditions aren't supported at all. I tried to use the `Condition` class and got:

```python
Traceback (most recent call last):
  File "/path/to/project/formations/custom_domain/custom_domain.py", line 71, in <module>
    print(template.to_json())
  File "/path/to/project/__pypackages__/3.9/lib/cottonformation/core/template.py", line 500, in to_json
    return json.dumps(self.to_dict(), indent=indent, ensure_ascii=False)
  File "/path/to/project/__pypackages__/3.9/lib/cottonformation/core/template.py", line 486, in to_dict
    dct = serialize(dct)
  File "/path/to/project/__pypackages__/3.9/lib/cottonformation/core/model.py", line 1025, in serialize
    return {
  File "/path/to/project/__pypackages__/3.9/lib/cottonformation/core/model.py", line 1026, in <dictcomp>
    key: serialize(nested_obj)
  File "/path/to/project/__pypackages__/3.9/lib/cottonformation/core/model.py", line 1025, in serialize
    return {
  File "/path/to/project/__pypackages__/3.9/lib/cottonformation/core/model.py", line 1026, in <dictcomp>
    key: serialize(nested_obj)
  File "/path/to/project/__pypackages__/3.9/lib/cottonformation/core/model.py", line 1018, in serialize
    return obj.serialize()
  File "/path/to/project/__pypackages__/3.9/lib/cottonformation/core/model.py", line 120, in serialize
    raise NotImplementedError
NotImplementedError
```

**Comment by MacHu-GWU** [comment]
@ipmb Good Catch, I think I need to implement this, I would like to do this in one week in the next version
